### ISSUE TITLE
操作対象およびセンサーのナンバリング

### ISSUE THREAD

**Issue by gotti** [ueckoken/plarail2021-soft#117]

**Comment by gotti** [comment]
ホールセンサーこんなのどう

```yaml
- name: "chofu_s1_b"
  predict: false //この先の位置予測を行うか
  stop: true //このホールセンサーと次のホールセンサーとの間に駅があるか
  nexts:
    - "chofu_s1_f"
- name: "chofu_s1_f"
  predict: false
  nexts:
    - "chofu_sagamihara"
    - "chofu_takao"
```
