### ISSUE TITLE
駅の初期化設定ファイル

### ISSUE THREAD

**Issue by Azuki-bar** [ueckoken/plarail2021-soft#201]
backend/external/pkg/syncController/embed/stationInit.yml にあります。

構文は以下の通りです。
```yaml
stations:
  - name: <駅名_b1>
    state: ON
```
name の引数は駅名_(b|s)数字 となっています。 bは分岐のためのサーボモータでsはストップレール制御用のサーボモータです。

~~stateは1がON, 2がOFFです。 サーボモータのON, OFFと一致します。~~
state は`ON`, `OFF`のどちらかの文字列を取ります。（仕様変更@ 20211115）

すべての駅に関して書いて欲しいです。詳細は @Azuki-bar に
