### ISSUE TITLE
駅の制約条件設定ファイルの記述

### ISSUE THREAD

**Issue by Azuki-bar** [ueckoken/plarail2021-soft#204]
```yaml
stations:
  - station:
      name: chofu_kudari
      points:
        - chofu_s1
        - chofu_s2
        - chofu_b1
        - chofu_b2
      rules:
        - on:
          off:
            - chofu_s1
            - chofu_s2
            - chofu_b1
            - chofu_b2
        - on:
            - chofu_s1
        - on:
            - chofu_s2
```
`- station:`以下に `name`, `points`, `rules`を要求します。
## name
デバッグ用に用いています。 分かりやすい名前を付けてください。
## points
制約条件に記述するサーボモータの名前を列挙します。
## rules
`on`, `off`が含まれるルールを複数指定できます。
ここでは`on`, `off`が最大1つ定義されたものを *rule* とします。
また *rule* を複数集めたものを *rules* とします。

*rule* のON, OFF はAND条件で効いてきます。記入しない場合は制約条件が無いものと見なします。

上の *rules* の1つ目の場合、chofu_s1, chofu_s2, chofu_b1, chofu_b2 の全てがOFFであるときに操作を許可します。

複数の rule が定義されている場合、各々の *rule* をどれか満たしたときに操作を許可します。
