### ISSUE TITLE
ESP32のアドレスと操作対象PINの設定ファイル

### ISSUE THREAD

**Issue by Azuki-bar** [ueckoken/plarail2021-soft#205]
# 見本

```yaml
stations:
  - station:
      name: chofu_b1
      address: http://example.com:80
      pin: 1
  - station:
      name: chofu_b2
      address: http://example.com:80
      pin: 2
      set_angle: true
      on_angle: 10
      off_angle: 100
```

# 仕様

## name(required)

制御するサーボモータの名前です。 plarail2021-soft/backend/proto/statesync.proto に名前の定義ファイルがあります。
命名規則は `<駅名>_<s|n><番号>`となっています。 s はストップレール、b は分岐器制御用のサーボモータです。

## address(required)

サーボモータを動かす ESP32 のアドレスを指定します。`http` は省略できません。ポート番号も忘れずに。

## pin(required)

ESP32 に制御させるピン番号を指定します。

## set_angle, on_angle, off_angle(optional)

もしサーボモータの ON,OFF に特別な角度の設定が必要ならば `set_angle`を true にしてください。
true に設定した場合 `on_angle`, `off_angle`の指定を行う必要があります。

`on_angle`, `off_angle` は 0 から 359 までの整数を要求します。
